<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JobTracker.Modules.Billing.Domain\JobTracker.Modules.Billing.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\JobTracker.SharedKernel\JobTracker.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Jobs\JobTracker.Modules.Jobs.IntegrationEvents\JobTracker.Modules.Jobs.IntegrationEvents.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
